[tool.cibuildwheel]
build-verbosity = 2

# Note: Tests are run within a docker container on Linux builds
# This will have a different
test-requires = "pytest scipy dask packaging"
# Import-mode=append to use installed (wheel) version of pyfftw
# rather than the local module
test-command = "pytest --import-mode=append {project}"

    [tool.cibuildwheel.environment]
    PIP_PREFER_BINARY = true

    [tool.cibuildwheel.windows]
    archs = [
        "AMD64",
        "x86",
    ]

    test-skip = [
        # Until SciPy does not support win32
        "*win32",

        # Until SciPy gives us PyPy wheels
        "pp*",
    ]

    [tool.cibuildwheel.macos]

    archs = [
        "x86_64",

        # See issue [#352](https://github.com/pyFFTW/pyFFTW/issues/352)
        # TODO: Add arm64 when we support it
        # Current problem seems to be that installed libfftw3 does not provide arm64
        # symbols
        # "universal2",
        # "arm64",
    ]

    test-skip = [
        # Until SciPy gives us PyPy wheels
        "pp*",
    ]

        [tool.cibuildwheel.macos.environment]
        CC = "/usr/bin/clang"
        CXX = "/usr/bin/clang++"
        CFLAGS = "-Wno-implicit-function-declaration -I/usr/local/opt/fftw/include"
        LDFLAGS = "-Wl,-S,-rpath,/usr/local/opt/fftw/lib -L/usr/local/opt/fftw/lib"

    # On Linux we need to use different package managers depending on image used
    [tool.cibuildwheel.linux]

    test-skip = [
        # See: https://github.com/pyFFTW/pyFFTW/issues/325
        "*i686",

        # See: https://github.com/pyFFTW/pyFFTW/issues/326
        "*aarch64",

        # Until SciPy gives us PyPy wheels
        "pp*",
    ]

    # Fallback, but we specify versions more explicitly below to achieve maximal
    # compatibility
    before-all = "yum install -y fftw-devel"

    manylinux-x86_64-image = "manylinux2014"
    manylinux-i686-image = "manylinux2014"
    manylinux-aarch64-image = "manylinux2014"
    manylinux-ppc64le-image = "manylinux2014"
    manylinux-s390x-image = "manylinux2014"
    manylinux-pypy_x86_64-image = "manylinux2014"
    manylinux-pypy_i686-image = "manylinux2014"
    manylinux-pypy_aarch64-image = "manylinux2014"

    archs = [
        "x86_64",
        "i686",
        "aarch64",
    ]

    # Select based on manylinux availability
    # See: https://github.com/pypa/manylinux
    # See: https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip
    # See: https://github.com/pypa/manylinux/issues/994#issuecomment-987835591
    # From 3.10+ we can stop doing the madness below and just PEP 600 manylinux_x_y images
    # Currently the selection of images is conservative and aims for maximal compatibility

    # Currently not supported
    # Even numpy does not support this
    # This is ignored in the wheel_tests_and_release.yml file
    # [[tool.cibuildwheel.overrides]]
    # select = "*-musllinux*"
    # before-all = "apk add fftw-dev"


[build-system]
requires = [
    "wheel",
    "setuptools",
    "Cython>=3",

    # NumPy dependencies - to update these, sync from
    # https://github.com/scipy/oldest-supported-numpy/
    # https://github.com/scipy/scipy/blob/master/pyproject.toml
    # and then
    # update minimum version to match our install_requires min version
    # ----------------------------------------------------------------

    # now matches minimum supported version, keep here as separate requirement
    # to be able to sync more easily with oldest-supported-numpy

    # loongarch64 requires numpy>=1.22.0
    "numpy==1.22.0; platform_machine=='loongarch64'",

    # On Windows we need to avoid 1.21.6, 1.22.0 and 1.22.1 because they were
    # built with vc142. 1.22.3 is the first version that has 32-bit Windows
    # wheels *and* was built with vc141. So use that:
    "numpy==1.22.3; python_version=='3.10' and platform_system=='Windows' and platform_python_implementation != 'PyPy'",

    # default numpy requirements
    "numpy==1.19.5; python_version=='3.9' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy'",
    # Note that 1.21.3 was the first version with a complete set of 3.10 wheels,
    # however macOS was broken and it's safe C API/ABI-wise to build against 1.21.6
    # (see oldest-supported-numpy issues gh-28 and gh-45)
    "numpy==1.21.6; python_version=='3.10' and (platform_system!='Windows' and platform_machine!='loongarch64') and platform_python_implementation != 'PyPy'",
    "numpy==1.23.2; python_version=='3.11' and platform_python_implementation != 'PyPy'",

    "numpy<2.0; python_version>='3.9' and platform_python_implementation=='PyPy'",
    "numpy<2.0; python_version>='3.12'",
]
build-backend = "setuptools.build_meta"
